### ISSUE TITLE
Preserve conversation ID across all published events

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/eShopOnContainers#15]
Currently some events are published outside of the handler and conversation ID is not preserved.

**Comment by weralabaj** [comment]
That is waiting for this issue https://github.com/Particular/NServiceBus/pull/4992, correct @MarcinHoppe ?

**Comment by MarcinHoppe** [comment]
Yes.

**Comment by MarcinHoppe** [comment]
It looks like this is best done after #7.

**Comment by MarcinHoppe** [comment]
This was done as a part of #7. Closing.
