### ISSUE TITLE
Document the journey of an order

### ISSUE THREAD

**Issue by kbaley** [Particular/eShopOnContainers#26]
In preparation for sagas, @dvdstelt and I followed the path of an order. Given the complexity of the code, I thought I'd document it at least in an issue first and we can figure out if we want to do anything with it.

Much of this will change with the saga implementation for orders but here's what we have so far:

- User checks out an order. This triggers a `UserCheckoutAcceptedIntegrationEvent`
- `UserCheckoutAcceptedIntegrationEventHandler`
  - publishes `OrderStartedIntegrationEvent` event, which empties the shoppingbasket in `Basket` service.
  - creates and publishes a `CreateOrderCommand` Mediatr command
- `CreateOrderCommandHandler` creates an `Order` and saves to the database
- `GracePeriodManagerService` runs as an `IHostedService`. Every 30 seconds (by default), it checks the database for submitted orders where the grace period (by default, 1 minute) has ended. For each order, it publishes a `GracePeriodConfirmedIntegrationEvent`
- `GracePeriodConfirmedIntegrationEventHandler` updates the order status to AwaitingValidation. Besides updating the orders status, this also adds an `OrderStatusChangedToAwaitingValidationDomainEvent` to the `Order` aggregates internal list of domain events
- `GracePeriodConfirmedIntegrationEventHandler` then saves the order to the database.
  - **IMPORTANT**: When saving the order, `OrderingContext` also dispatches any pending domain events
- `OrderStatusChangedToAwaitingValidationDomainEventHandler` kicks in, verifies stock, then publishes `OrderStatusChangedToAwaitingValidationIntegrationEvent`
- `OrderStatusChangedToAwaitingValidationIntegrationEventHandler` (in Catalog.API) checks stock and publishes `OrderStockRejectedIntegrationEvent` or `OrderStockConfirmedIntegrationEvent` accordingly

### Stock rejected
- `OrderStockRejectedIntegrationEventHandler` collects rejected items, sets order status to `Cancelled`, and saves the order. No other work is performed

### Stock confirmed
- `OrderStockConfirmedIntegrationEventHandler` sets the order status to "confirmed" which adds an `OrderStatusChangedToStockConfirmedDomainEvent` to the order aggregate.
- `OrderStockConfirmedIntegrationEventHandler` saves the order which triggers the domain event in the previous step in Mediatr
- `OrderStatusChangedToStockConfirmedDomainEventHandler` publishes an `OrderStatusChangedToStockConfirmedIntegrationEvent`
- `OrderStatusChangedToStockConfirmedIntegrationEventHandler` (in Payment.API) publishes either `OrderPaymentSuccededIntegrationEvent` _(sic)_ or `OrderPaymentFailedIntegrationEvent`
- `OrderPaymentFailedIntegrationEventHandler marks the order as cancelled and saves it
- `OrderPaymentSuccededIntegrationEventHandler` marks the order as paid, which adds an `OrderStatusChangedToPaidDomainEvent` to the order aggregate. The handler then saves the order which triggers the domain event.
- `OrderStatusChangedToPaidDomainEventHandler` triggers an `OrderStatusChangedToPaidIntegrationEvent`
- `OrderStatusChangedToPaidIntegrationEventHandler` (in Catalog.API) updates the stock

**Comment by dvdstelt** [comment]
Awesome job @kbaley, it was surprisingly difficult to wade through the code and figure out what was happening when.
I mean, `DispatchDomainEvents` inside the `SaveChanges()` method on a custom `DbContext`? And then some...

**Comment by dvdstelt** [comment]
Go to https://www.websequencediagrams.com/
Then paste the following

```
title eShopOnContainers ordering process

Basket->Ordering: UserCheckoutAcceptedIE
Ordering->+Ordering: CreateOrderCommand
Ordering->Ordering: OrderStartedDomainEvent
Ordering->Ordering: BuyerAndPaymentMethodVerifiedDomainEvent
Ordering->-Basket: OrderStartedIE
note left of Basket
    Empties
    ShoppingCart
end note
Ordering->+Ordering: OrderStatusChangedToAwaitingValidationDE
Ordering->-Catalog: OrderStatusChangedToAwaitingValidationIE
Catalog->+Ordering: OrderStockConfirmedIE
Ordering->Ordering: OrderStatusChangedToStockConfirmedDE
Ordering->-Payment: OrderStatusChangedToStockConfirmedIE
Payment->+Ordering: OrderPaymentSuccededIE
note left of Ordering
    here we set order
    as being paid
end note
Ordering->Ordering: OrderStatusChangedToPaidDE
Ordering->-Catalog: OrderStatusChangedToPaidIE
note right of Catalog
    Only now do we
    reduce stock
    race condition any1?
end note
```

And it becomes a little more clear what is happening.
Sometimes `integration events` are coming in and we do database updates and then do other actions. Sometimes there are only domain events and then we first publish the domain event and then we do actions, like updating the status. This mixing and matching makes it little harder to read.

**Comment by dvdstelt** [comment]
This (saga) is done and can be closed.
